### ISSUE TITLE
WAT?!

### ISSUE THREAD

**Issue by Chamberlain91** [kirypto/wat.js#2]
I DON'T SEE A CONWATS GAME OF WAAT EXAMPLE PROGRAM. SHAME.

**Comment by kirypto** [comment]
Yeah, I’ve sorta let development on this slide in the recent past. I’ll pick this up again and work on that. Thanks for showing interest!

**Comment by kirypto** [comment]
Working on this now! Hoping to have helloWat.js example up next week!

**Comment by kirypto** [comment]
Hmm, miss-read the top message last time I was here. Was thinking it was just asking for an example. 
Anyway, Hello, Wat! is done now. I'm going to close this issue and spin up a new one for the Conway's Game of Wat.
